blank_issues_enabled: true
contact_links:
  - name: Rule-related issues
    url: https://github.com/xojs/eslint-config-xo/issues
    about: For issues about specific rules (enabling/disabling a rule, rule behavior, requesting a new rule), use the eslint-config-xo issue tracker.
